name: Streamlit CI/CD

on:
  push:
    branches:
      [main, app_dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploying to streamlit
      # This step uses a marketplace action for Streamlit-specific testing
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          docker_file : Dockerfile
          docker_file_directory : .
          process_type : web
          app-file: app.py # Replace with the name of your main Streamlit file
          # Optional: Add other commands, e.g., 'pytest' if you have unit tests
          # command: pytest 